apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: regression-test-with-npu
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
    - name: furiosa-models-dataset
      mountPath: /furiosa-models-dataset
  params:
    - name: GITHUB_TOKEN_SECRET_NAME
      description: |
        The name of the Kubernetes Secret that contains the GitHub token.
      type: string
      default: github
    - name: GITHUB_TOKEN_SECRET_KEY
      description: |
        The key within the Kubernetes Secret that contains the GitHub token.
      type: string
      default: token
    - name: prNumber
      description: The corresponding pr number
    - name: modelName
      description: Name of the model to run the regression test
  steps:
    - name: regression-test-with-npu
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://pypi.corp.furiosa.ai/simple"
        - name: "GH_TOKEN"
          valueFrom:
            secretKeyRef:
              name: $(params.GITHUB_TOKEN_SECRET_NAME)
              key: $(params.GITHUB_TOKEN_SECRET_KEY)
      image: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:base
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -ex

        # Install toolchain
        apt update && make toolchain

        # Install furiosa-models package
        pip install --constraint ci-constraints.txt .[test,full]

        git config --global --add safe.directory /workspace/source
        echo -n "## Pip freeze result for " > pip_freeze.txt
        echo $(params.modelName) >> pip_freeze.txt
        echo "<details><summary>pip freeze result</summary><pre>" >> pip_freeze.txt
        pip freeze >> pip_freeze.txt
        echo "</pre></details>" >> pip_freeze.txt
        gh issue comment $(params.prNumber) --body-file pip_freeze.txt

        rm -rf tests/data
        ln -s /furiosa-models-dataset tests/data
        make regression-test-$(params.modelName)

        git log -n1 --format="%C(auto) %h %s" > report.txt
        echo "\`\`\`" >> report.txt
        py.test-benchmark compare >> report.txt
        echo "\`\`\`" >> report.txt

        gh issue comment $(params.prNumber) --body-file report.txt

      resources:
        requests:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
