site_name: Furiosa Models
site_description: DNN Models optimized for FuriosaAI NPU
site_url: https://furiosa-ai.github.io/furiosa-models

theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: "material"
  features:
    - navigation.sections
  palette:
      primary: custom
      accent: custom
extra_css:
  - stylesheets/extra.css

repo_name: furiosa-ai/furiosa-models
repo_url: https://github.com/furiosa-ai/furiosa-models

nav:
- Overview: index.md
- getting_started.md
- Tutorials:
  - tutorials/navigate_models.ipynb
  - tutorials/quantize_and_compile_model.ipynb
  - tutorials/serving_with_furiosa_serving.md
- model_object.md
- command_line_tool.md
- Models:
    - models/resnet50_v1.5.md
    - models/efficientnet_b0.md
    - models/efficientnet_v2_s.md
    - models/ssd_mobilenet.md
    - models/ssd_resnet34.md
    - models/yolov5m.md
    - models/yolov5l.md
- Changelog: changelog.md
- Developer's guide: developers_guide.md
- Apache License 2.0: 'https://github.com/furiosa-ai/furiosa-models/blob/main/LICENSE'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
- search
- mkdocs-jupyter:
    ignore: ["examples/*.py"]
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: false
          show_bases: false
