site_name: Furiosa Models
site_description: DNN Models optimized for FuriosaAI NPU
site_url: https://furiosa-ai.github.io/furiosa-models-experimental

theme:
  name: material

repo_name: furiosa-ai/furiosa-models-experimental
repo_url: https://github.com/furiosa-ai/furiosa-models-experimental

nav:
- Overview: index.md
- Models:
    - Image Classification:
        - models/resnet50_v1.5.md
    - Object Detection:
        - models/ssd_mobilenet.md
        - models/ssd_resnet34.md
- blocking_and_nonblocking_api.md
- "NPU-optimized Postprocessor": native_postprocessor.md
- changelog.md
- Apache License 2.0: 'https://github.com/furiosa-ai/furiosa-models-experimental/blob/main/LICENSE'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
