apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: furiosa-models-ci
  namespace: ci-furiosa-models
spec:
  params:
    - name: repo_full_name
      description: The git repository name
    - name: gitRepository
      description: The git repository that hosts context and Dockerfile
      default: git@github.com:furiosa-ai/furiosa-models.git
    - name: gitRevision
      description: The Git revision to be used.
      default: master
    - name: triggerContext
      description: Trigger context came from status trigger binding
    - name: headRef
      description: The git head ref (branch name)
    - name: gitCloneDepth
      description: Number of commits in the change + 1
      default: "1"

  resources:
    - name: image
      type: image

  workspaces:
    - name: source
      description: Workspace where the git repo is prepared for testing
    - name: furiosa-apt-credential
      description: APT credential for FuriosaAI private repository
    - name: aws-credential
      description: AWS credentials for s3 access
    - name: internal-pypi-secret
      description: For internal pypi access
    - name: furiosa-models-dvc-cache
      description: furiosa-models dvc cache
    - name: furiosa-models-pip-cache
      description: furiosa-models pip cache
    - name: furiosa-models-compiler-cache
      description: furiosa-models compiler cache

  tasks:
  - name: set-status-begin
    taskRef:
      name: github-set-status
    params:
    - name: REPO_FULL_NAME
      value: $(params.repo_full_name)
    - name: SHA
      value: $(params.gitRevision)
    - name: TARGET_URL
      value: https://tekton.office.furiosa.in/#/namespaces/ci-furiosa-models/pipelineruns/$(context.pipelineRun.name)
    - name: GITHUB_TOKEN_SECRET_NAME
      value: "github-credential"
    - name: GITHUB_TOKEN_SECRET_KEY
      value: "password"
    - name: DESCRIPTION
      value: "begin"
    - name: CONTEXT
      value: "furiosa-models-ci"
    - name: STATE
      value: pending

  - name: clone
    taskRef:
      name: git-clone
    workspaces:
      - name: output
        workspace: source
    params:
    - name: url
      value: $(params.gitRepository)
    - name: revision
      value: $(params.gitRevision)
    - name: depth
      value: $(params.gitCloneDepth)

  - name: lint
    taskRef:
      name: lint
    workspaces:
      - name: source
        workspace: source
    params:
    - name: logs
      value: "https://grafana.office.furiosa.in/d/logs/kubernetes-pod-logs?orgId=1&var-pod=$(context.pipelineRun.name)-format"
    - name: pod-resource-usage
      value: "https://grafana.office.furiosa.in/d/pod-resource-usage/k8s-pod-resource-dashboard?orgId=1&var-namespace=ci-furiosa-models&var-pod=$(context.pipelineRun.name)-format-pod"
    runAfter:
      - clone

  - name: build-and-push
    taskRef:
      name: build-and-push
    workspaces:
      - name: source
        workspace: source
      - name: furiosa-apt-credential
        workspace: furiosa-apt-credential
    params:
    - name: DOCKERFILE
      value: "Dockerfile"
    - name: logs
      value: "https://grafana.office.furiosa.in/d/logs/kubernetes-pod-logs?orgId=1&var-pod=$(context.pipelineRun.name)-build-and-push"
    - name: pod-resource-usage
      value: "https://grafana.office.furiosa.in/d/pod-resource-usage/k8s-pod-resource-dashboard?orgId=1&var-namespace=ci-furiosa-models&var-pod=$(context.pipelineRun.name)-build-and-push-pod"
    resources:
      outputs:
        - name: image
          resource: image
    runAfter:
      - lint

  - name: unittests
    taskRef:
      name: unittests
    workspaces:
      - name: source
        workspace: source
      - name: furiosa-apt-credential
        workspace: furiosa-apt-credential
      - name: aws-credential
        workspace: aws-credential
      - name: internal-pypi-secret
        workspace: internal-pypi-secret
        subPath: .netrc
      - name: furiosa-models-dvc-cache
        workspace: furiosa-models-dvc-cache
      - name: furiosa-models-pip-cache
        workspace: furiosa-models-pip-cache
      - name: furiosa-models-compiler-cache
        workspace: furiosa-models-compiler-cache
    params:
    - name: logs
      value: "https://grafana.office.furiosa.in/d/logs/kubernetes-pod-logs?orgId=1&var-pod=$(context.pipelineRun.name)-unittests-pod"
    - name: pod-resource-usage
      value: "https://grafana.office.furiosa.in/d/pod-resource-usage/k8s-pod-resource-dashboard?orgId=1&var-namespace=ci-furiosa-models&var-pod=$(context.pipelineRun.name)-unittests-pod"
    resources:
      inputs:
        - name: image
          resource: image
    runAfter:
      - build-and-push

  - name: test-examples
    taskRef:
      name: test-examples
    workspaces:
      - name: source
        workspace: source
      - name: furiosa-apt-credential
        workspace: furiosa-apt-credential
      - name: aws-credential
        workspace: aws-credential
      - name: internal-pypi-secret
        workspace: internal-pypi-secret
        subPath: .netrc
      - name: furiosa-models-dvc-cache
        workspace: furiosa-models-dvc-cache
      - name: furiosa-models-pip-cache
        workspace: furiosa-models-pip-cache
      - name: furiosa-models-compiler-cache
        workspace: furiosa-models-compiler-cache
    params:
      - name: logs
        value: "https://grafana.office.furiosa.in/d/logs/kubernetes-pod-logs?orgId=1&var-pod=$(context.pipelineRun.name)-test-examples-pod"
      - name: pod-resource-usage
        value: "https://grafana.office.furiosa.in/d/pod-resource-usage/k8s-pod-resource-dashboard?orgId=1&var-namespace=ci-furiosa-models&var-pod=$(context.pipelineRun.name)-test-examples-pod"
    resources:
      inputs:
        - name: image
          resource: image
    runAfter:
      - build-and-push

  finally:
  - name: set-status-success
    taskRef:
      name: github-set-status
    params:
    - name: REPO_FULL_NAME
      value: $(params.repo_full_name)
    - name: SHA
      value: $(params.gitRevision)
    - name: TARGET_URL
      value: https://tekton.office.furiosa.in/#/namespaces/ci-furiosa-models/pipelineruns/$(context.pipelineRun.name)
    - name: GITHUB_TOKEN_SECRET_NAME
      value: "github-credential"
    - name: GITHUB_TOKEN_SECRET_KEY
      value: "password"
    - name: DESCRIPTION
      value: "succeeded"
    - name: CONTEXT
      value: "furiosa-models-ci"
    - name: STATE
      value: success
    when:
    - input: $(tasks.status)
      operator: notin
      values: ["Failed"]
  - name: set-status-failed
    taskRef:
      name: github-set-status
    params:
    - name: REPO_FULL_NAME
      value: $(params.repo_full_name)
    - name: SHA
      value: $(params.gitRevision)
    - name: TARGET_URL
      value: https://tekton.office.furiosa.in/#/namespaces/ci-furiosa-models/pipelineruns/$(context.pipelineRun.name)
    - name: GITHUB_TOKEN_SECRET_NAME
      value: "github-credential"
    - name: GITHUB_TOKEN_SECRET_KEY
      value: "password"
    - name: DESCRIPTION
      value: "failed"
    - name: CONTEXT
      value: "furiosa-models-ci"
    - name: STATE
      value: failure
    when:
    - input: $(tasks.status)
      operator: in
      values: ["Failed"]
