apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unittests
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
  params:
    - name: image
      description: The container image to use black in
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:v0.8.0
  steps:
    - name: unittests
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e

        cd /workspace/source

        pip install --pre .[test]
        make unit_tests

      resources:
        requests:
          memory: 16Gi
          cpu: 8
        limits:
          memory: 16Gi
          cpu: 8
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-examples
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
  params:
    - name: image
      description: The container image to use black in
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:v0.8.0
  steps:
    - name: run
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e

        TOOLCHAIN_VERSION=$(apt-cache policy furiosa-libcompiler | grep Installed | awk '{print $2}')
        apt-get update && apt-get install -y furiosa-libhal-sim=$TOOLCHAIN_VERSION

        cd /workspace/source

        pip install --pre .
        NPU_GLOBAL_CONFIG_PATH=warboy-2pe make examples

      resources:
        requests:
          memory: 16Gi
          cpu: 8
        limits:
          memory: 16Gi
          cpu: 8
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: regression-test-with-npu
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
    - name: furiosa-models-dataset
      mountPath: /furiosa-models-dataset
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:v0.8.0
    - name: modelName
      description: Name of the model to run the regression test
  steps:
    - name: regression-test-with-npu
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        cd /workspace/source

        rm -rf tests/data
        ln -s /furiosa-models-dataset tests/data

        pip install --pre .[test]

        make regression-test-$(params.modelName)

      resources:
        requests:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: regression-test-report
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:v0.8.0
    - name: reportFileName
      description: Name of the file to save the report data
      default: report.txt
  steps:
    - name: regression-test-report
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        pip install --quiet pytest-benchmark

        cd /workspace/source

        git log -n1 --format="%C(auto) %h %s" > $(workspaces.source.path)/$(params.reportFileName)
        echo "\`\`\`" >> $(workspaces.source.path)/$(params.reportFileName)
        py.test-benchmark compare >> $(workspaces.source.path)/$(params.reportFileName)
        echo "\`\`\`" >> $(workspaces.source.path)/$(params.reportFileName)

      resources:
        requests:
          memory: 8Gi
          cpu: 4
        limits:
          memory: 8Gi
          cpu: 4
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-dvc-cache
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:v0.8.0
  steps:
    - name: set-dvc-cache
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        cd /workspace/source
        ln -s /dvc-cache/furiosa-models ./.dvc/cache

      resources:
        requests:
          memory: 8Gi
          cpu: 4
        limits:
          memory: 8Gi
          cpu: 4
