apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: format-build-unittests
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
  params:
    - name: image
      description: The container image to use black in
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:latest
  steps:
    - name: format
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
        - name: "TOOLCHAIN_VERSION"
          value: "0.8.0-2+nightly-220827"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e

        rm -rf /root/.cache/pip
        mkdir -p /root/.cache
        ln -s /dvc-cache/pip /root/.cache/pip

        cd /workspace/source
        export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 814F888B20B09A7E

        tee /etc/apt/sources.list.d/furiosa.list << EOF
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal restricted
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal-nightly restricted
        EOF

        apt update && apt-get install -y libonnxruntime furiosa-libhal-warboy \
            furiosa-libcompiler=$TOOLCHAIN_VERSION furiosa-libnux-extrinsic=$TOOLCHAIN_VERSION \
            furiosa-libnux=$TOOLCHAIN_VERSION

        make lint
        pip3 install --pre --editable .[test]
        make unit_tests

      resources:
        requests:
          memory: 32Gi
          cpu: 16
        limits:
          memory: 32Gi
          cpu: 16
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: regression-test-with-npu
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:latest
  steps:
    - name: regression-test-with-npu
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
        - name: "TOOLCHAIN_VERSION"
          value: "0.8.0-2+nightly-220827"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        rm -rf /root/.cache/pip
        mkdir -p /root/.cache
        ln -s /dvc-cache/pip /root/.cache/pip

        cd /workspace/source
        export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

        apt-key adv --keyserver keyserver.ubuntu.com --recv-key 5F03AFA423A751913F249259814F888B20B09A7E && \
        tee /etc/apt/sources.list.d/furiosa.list << EOF
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal restricted
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal-nightly restricted
        EOF

        apt update && apt-get install -y libonnxruntime furiosa-libhal-warboy \
            furiosa-libcompiler=$TOOLCHAIN_VERSION furiosa-libnux-extrinsic=$TOOLCHAIN_VERSION \
            furiosa-libnux=$TOOLCHAIN_VERSION
        pip3 install --pre -e .[test]

        make regression_tests

      resources:
        requests:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-dvc-cache
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: aws-credential
      mountPath: /root/.aws
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:latest
  steps:
    - name: set-dvc-cache
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        cd /workspace/source
        ln -s /dvc-cache/furiosa-models ./.dvc/cache

      resources:
        requests:
          memory: 32Gi
          cpu: 16 
        limits:
          memory: 32Gi
          cpu: 16
