apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: format-build-unittests
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
  params:
    - name: image
      description: The container image to use black in
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:latest
  steps:
    - name: format
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e

        rm -rf /root/.cache/pip
        mkdir -p /root/.cache
        ln -s /dvc-cache/pip /root/.cache/pip

        cd /workspace/source

        make lint
        pip3 install --pre --editable .[test]
        make unit_tests

      resources:
        requests:
          memory: 32Gi
          cpu: 16
        limits:
          memory: 32Gi
          cpu: 16
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: regression-test-with-npu
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:latest
  steps:
    - name: regression-test-with-npu
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        rm -rf /root/.cache/pip
        mkdir -p /root/.cache
        ln -s /dvc-cache/pip /root/.cache/pip

        cd /workspace/source

        pip3 install --pre -e .[test]

        make regression_tests

      resources:
        requests:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-dvc-cache
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: aws-credential
      mountPath: /root/.aws
  params:
    - name: image
      description: The container image
      default: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:latest
  steps:
    - name: set-dvc-cache
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        cd /workspace/source
        ln -s /dvc-cache/furiosa-models ./.dvc/cache

      resources:
        requests:
          memory: 32Gi
          cpu: 16 
        limits:
          memory: 32Gi
          cpu: 16
