apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: format-build-unittests
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: internal-pypi-secret
      mountPath: /root/.netrc
  params:
    - name: image
      description: The container image to use black in
      default: python:3.9-bullseye
  steps:
    - name: format
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
        - name: "TOOLCHAIN_VERSION"
          value: "0.8.0-2+nightly-220827"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e

        cd /workspace/source
        export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

        apt-get update && apt-get install -y build-essential pkg-config \
        libssl-dev ca-certificates apt-transport-https libclang-dev \
        python3-dev cmake protobuf-compiler gnupg
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 814F888B20B09A7E

        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        source "$HOME/.cargo/env"

        tee /etc/apt/sources.list.d/furiosa.list << EOF
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal restricted
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal-nightly restricted
        EOF

        apt update && apt-get install -y libonnxruntime furiosa-libhal-warboy \
            furiosa-libcompiler=$TOOLCHAIN_VERSION furiosa-libnux-extrinsic=$TOOLCHAIN_VERSION \
            furiosa-libnux=$TOOLCHAIN_VERSION
        python -m pip install --upgrade pip wheel setuptools Cython pytest pycocotools
        python -m pip install black isort

        make lint
        python -m pip install --pre --editable .[test]
        make unit_tests

      resources:
        requests:
          memory: 32Gi
          cpu: 16
        limits:
          memory: 32Gi
          cpu: 16
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: regression-test-with-npu
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
  params:
    - name: image
      description: The container image
      default: python:3.9-bullseye
  steps:
    - name: regression-test-with-npu
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
        - name: "TOOLCHAIN_VERSION"
          value: "0.8.0-2+nightly-220827"
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        cd /workspace/source
        export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

        apt-get update && \
        apt-get install -y apt-transport-https ca-certificates git gnupg curl \
        build-essential pkg-config libssl-dev libclang-dev python3-dev cmake \
        protobuf-compiler

        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        source "$HOME/.cargo/env"

        apt-key adv --keyserver keyserver.ubuntu.com --recv-key 5F03AFA423A751913F249259814F888B20B09A7E && \
        tee /etc/apt/sources.list.d/furiosa.list << EOF
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal restricted
        deb [arch=amd64] https://internal-archive.furiosa.dev/ubuntu focal-nightly restricted
        EOF

        apt update && apt-get install -y libonnxruntime furiosa-libhal-warboy \
            furiosa-libcompiler=$TOOLCHAIN_VERSION furiosa-libnux-extrinsic=$TOOLCHAIN_VERSION \
            furiosa-libnux=$TOOLCHAIN_VERSION
        python -m pip install --upgrade pip wheel setuptools Cython pytest pycocotools
        python -m pip install --pre -e .[test]
        python -m pip install dvc[s3]

        make regression_tests

      resources:
        requests:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 32Gi
          cpu: 16
          alpha.furiosa.ai/npu: 1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: set-dvc-cache
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: aws-credential
      mountPath: /root/.aws
  params:
    - name: image
      description: The container image
      default: python:3.9-bullseye
  steps:
    - name: set-dvc-cache
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -e
        set -x

        cd /workspace/source
        ln -s /dvc-cache/furiosa-models ./.dvc/cache

      resources:
        requests:
          memory: 32Gi
          cpu: 16 
        limits:
          memory: 32Gi
          cpu: 16
