apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:lint
      imagePullPolicy: Always
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -e

        make lint

      resources:
        requests:
          memory: 4Gi
          cpu: 4
        limits:
          memory: 4Gi
          cpu: 4
