apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unittests
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
  steps:
    - name: unittests-and-document-notebook-test
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://pypi.corp.furiosa.ai/simple"
      image: asia-northeast3-docker.pkg.dev/next-gen-infra/furiosa-ai/furiosa-models:base
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -e

        # Install toolchain
        apt update && make toolchain

        # Install furiosa-models package
        pip install --constraint ci-constraints.txt .[test,full]

        make unit_tests
        make notebook_tests
        make examples

      resources:
        requests:
          memory: 16Gi
          cpu: 8
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 16Gi
          cpu: 8
          alpha.furiosa.ai/npu: 1
