apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unittests
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - name: unittests-and-document-notebook-test
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(resources.inputs.image.url)
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -e

        # FIXME: Remove me when TLS problem is solved (https://github.com/furiosa-ai/furiosa-sdk-private/issues/719)
        export LD_PRELOAD=$(find $(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')/torch/lib/ -name "libgomp*"):$LD_PRELOAD
        make unit_tests
        make notebook_tests

      resources:
        requests:
          memory: 16Gi
          cpu: 8
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 16Gi
          cpu: 8
          alpha.furiosa.ai/npu: 1
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-examples
  namespace: ci-furiosa-models
spec:
  workspaces:
    - name: source
    - name: furiosa-apt-credential
      mountPath: /etc/apt/auth.conf.d
      readOnly: true
    - name: aws-credential
      mountPath: /root/.aws
    - name: internal-pypi-secret
      mountPath: /root/.netrc
      readOnly: true
    - name: furiosa-models-dvc-cache
      mountPath: /dvc-cache
    - name: furiosa-models-pip-cache
      mountPath: /root/.cache/pip
    - name: furiosa-models-compiler-cache
      mountPath: /root/.cache/furiosa
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - name: run
      env:
        - name: "PIP_EXTRA_INDEX_URL"
          value: "https://internal-pypi.furiosa.dev/simple"
      image: $(resources.inputs.image.url)
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -e

        # FIXME: Remove me when TLS problem is solved (https://github.com/furiosa-ai/furiosa-sdk-private/issues/719)
        export LD_PRELOAD=$(find $(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')/torch/lib/ -name "libgomp*"):$LD_PRELOAD
        make examples

      resources:
        requests:
          memory: 16Gi
          cpu: 8
          alpha.furiosa.ai/npu: 1
        limits:
          memory: 16Gi
          cpu: 8
          alpha.furiosa.ai/npu: 1
